// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeQ_bKiEpj3bKc-7rJzYeuL8aYA19bTgU',
    appId: '1:512794359842:android:67954f7ea68253af37b27b',
    messagingSenderId: '512794359842',
    projectId: 'pinwinos-tamaulipas',
    storageBucket: 'pinwinos-tamaulipas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3isU6ONQBworCov-B_CBrOCATMeJcoHU',
    appId: '1:512794359842:ios:870b07e05587c83537b27b',
    messagingSenderId: '512794359842',
    projectId: 'pinwinos-tamaulipas',
    storageBucket: 'pinwinos-tamaulipas.appspot.com',
    iosBundleId: 'com.example.pinwinos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3isU6ONQBworCov-B_CBrOCATMeJcoHU',
    appId: '1:512794359842:ios:7fb5b1e145b8ae2f37b27b',
    messagingSenderId: '512794359842',
    projectId: 'pinwinos-tamaulipas',
    storageBucket: 'pinwinos-tamaulipas.appspot.com',
    iosBundleId: 'com.example.pinwinos.RunnerTests',
  );
}
